name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: |
          ssh ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }} << 'EOF'
          cd /backend
          git pull origin main
          npm install
          npm run build
          pm2 restart all || pm2 start src/index.js --name backend
          EOF

      - name: Deploy Frontend
        run: |
          ssh ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }} << 'EOF'
          cd /frontend
          git pull origin main
          npm install
          npm run build
          pm2 restart all || pm2 start npm --name "frontend" -- start
          EOF
