name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          AWS_SSH_HOST: ${{ secrets.AWS_SSH_HOST }}
          AWS_SSH_USER: ${{ secrets.AWS_SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > ~/.ssh/github
          chmod 600 ~/.ssh/github
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.AWS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Pull Latest Code
        run: |
          ssh -i ~/.ssh/github -o StrictHostKeyChecking=no ${{ secrets.AWS_SSH_USER }}@${{ secrets.AWS_SSH_HOST }} << 'EOF'

      - name: Install Dependencies and Deploy Backend
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          cd /backend
          npm install
          pm2 restart all || pm2 start dist/main.js --name backend --env production
          EOF

      - name: Install Dependencies and Deploy Frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          cd /frontend
          npm install
          npm run build
          pm2 restart all || pm2 start npm --name "frontend" -- start
          EOF
